import { SPECIES } from './species.js';

// WEBP => "Lumber.webp"
// --------------------
// Name => "Lumber"
// IMG => "R_Lumber"
// ID.data_attr => "data-lumber"
// ID.resources => "#resLumber"
// ID.market => "#market-Lumber"
// ID.storage => "#stack-Lumber"
// ID.eject => "#eject-Lumber"

// Generated by parsing 'https://pmotschmann.github.io/Evolve/' (main game page).
const all_resources = [
    'AICore', //? Missing
    'Adamantite',
    'Aerogel',
    'Alloy',
    'Aluminium',
    'AntiPlasmid', //? Missing
    'Artifact', //? Missing
    'Asphodel_Powder', //? Missing
    'Authority', //? Missing
    'Blessed_Essence', //? Missing
    'Blood_Stone', //? Missing
    'Bolognium',
    'Brick',
    'Cement',
    'Chrysotile', //? Missing
    'Cipher', //? Missing
    'Coal',
    'Codex', //? Missing
    'Containers',
    'Copper',
    'Corrupt_Gem',
    'Crates',
    'Crystal', //? Missing
    'Dark', //? Missing
    'Demonic_Essence', //? Missing
    'Deuterium',
    'Elerium',
    'Elysanite', //? Missing
    'Energy', //? Missing
    'Food',
    'Furs',
    'Genes',
    'Graphene',
    'Harmony',
    'Helium_3',
    'Horseshoe',
    'Infernite',
    'Iridium',
    'Iron',
    'Knockoff', //? Missing
    'Knowledge',
    'Lumber',
    'Mana', //? Missing
    'Materials', //? Missing
    'Money',
    'Mythril',
    'Nanite', //? Missing
    'Nano_Tube',
    'Nanoweave',
    'Neutronium',
    'Oil',
    'Omniscience', //? Missing
    'Orichalcum',
    'Phage',
    'Plasmid',
    'Plywood',
    'Polymer',
    'Quantium', //? Missing
    'Scarletite', //? Missing
    'Sheet_Metal',
    'Slave', //? Missing
    'Soul_Gem',
    'Stanene',
    'Steel',
    'Stone',
    'Supercoiled', //? Missing
    'Sus', //? Missing
    'Titanium',
    'Unobtainium', //? Missing
    'Uranium',
    'Useless', //? Missing
    'Vitreloy',
    'Water', //? Missing
    'Wrought_Iron',
    'Zen', //? Missing
];

const resources = all_resources.map((resource_name) => {
    // Name is the uppercase version of the resource name
    // e.g. "Lumber"

    return {
        name: resource_name,
        img: `R_${resource_name}`,
        id: {
            data_attr: `data-${resource_name.toLowerCase()}`,
            resources: `#res${resource_name}`,
            market: `#market-${resource_name}`,
            storage: `#stack-${resource_name}`,
            eject: `#eject${resource_name}`,
        },
    };
});

const species_as_resources = SPECIES.map((species) => {
    // Species is the uppercase version of the species name.
    // e.g. "Troll"

    return {
        name: species,
        img: 'R_Population',
        id: {
            data_attr: `data-${species.toLowerCase()}`,
            resources: `#res${species.toLowerCase()}`, //! Must be lowercase.
            market: `#market-${species}`,
            storage: `#stack-${species}`,
            eject: `#eject${species}`,
        },
    };
});

export const RESOURCES = [...resources, ...species_as_resources];


export function find_resource_by_name(name: string) {
    return RESOURCES.find((resource) => resource.name === name);
}
export function find_resource_by_data_attr(data_attr: string) {
    return RESOURCES.find((resource) => resource.id.data_attr === data_attr);
}
export function find_resource_by_resource_id(id: string) {
    return RESOURCES.find((resource) => resource.id.resources === id);
}
export function find_resource_by_market_id(id: string) {
    return RESOURCES.find((resource) => resource.id.market === id);
}
export function find_resource_by_storage_id(id: string) {
    return RESOURCES.find((resource) => resource.id.storage === id);
}
export function find_resource_by_eject_id(id: string) {
    return RESOURCES.find((resource) => resource.id.eject === id);
}